<script type="text/javascript">
    //<![CDATA[
    function doSetup() {
        new Ajax.Request('<?php echo $this->getAjaxSetupUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
                button = $('loyaltylion_setup_button');
                button.removeClassName('fail').addClassName('success');
                button.update("Success");
            }
        });
    }
    //]]>
</script>
 
<?php echo $this->getButtonHtml() ?>
