<script type="text/javascript">
    //<![CDATA[
    function doSetup() {
        button = $('loyaltylion_setup_button');
        new Ajax.Request('<?php echo $this->getAjaxSetupUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
                switch (transport.responseText) {
                case "ok":
                    button.removeClassName('fail').addClassName('success');
                    button.update("Success");
                    break;
                case "already-done":
                    button.removeClassName('fail').removeClassName('success');
                    button.update("API access is already configured");
                    break;
                case "not-configured-yet":
                    button.removeClassName('fail').removeClassName('success');
                    button.update("Please save your Token / Secret first");
                    break;
		default:
                    button.removeClassName('success').addClassName('fail');
		    button.update("Error");
                }
            },
            onError: function(transport){
                button.removeClassName('success').addClassName('fail');
                button.update("Error");
            }
        });
    }
    //]]>
</script>
 
<?php echo $this->getButtonHtml() ?>
