<?php if ($this->isEnabled()): ?>
<script>(function(t,e){window.lion=e;var n,i=t.getElementsByTagName("script")[0];n=t.createElement("script"),n.type="text/javascript",n.async=!0,n.src="//<?php echo $this->getSDKUrl() ?>",i.parentNode.insertBefore(n,i),e.init=function(n){function i(t,e){var n=e.split(".");2===n.length&&(t=t[n[0]],e=n[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}var r,o=t.getElementsByTagName("script")[0];r=t.createElement("script"),r.type="text/javascript",r.async=!0,r.src="//<?php echo $this->getPlatformHost() ?>/sdk/configuration/"+n+".js",o.parentNode.insertBefore(r,o),e.ui=e.ui||[];for(var a="_push configure track_pageview identify_customer auth_customer identify_product on off ui.refresh".split(" "),c=0;a.length>c;c++)i(e,a[c]);e._token=n}})(document,window.lion||[]);

lion.init("<?php echo $this->getToken() ?>"); lion.configure({ platform: 'magento' });
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
  <?php
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $now = date('c');
    $auth_src = $customer->getId() . $now . $this->getSecret();
  ?>
  lion.identify_customer({ id: "<?php echo $customer->getId() ?>", email: "<?php echo $customer->getEmail() ?>", name: "<?php echo $customer->getName() ?>" });
  lion.auth_customer({ date: "<?php echo $now ?>", auth_token: "<?php echo sha1($auth_src) ?>" });
<?php endif ?>
</script>
<?php endif ?>