<?php if ($this->isEnabled()): ?>
  <script>
    !function(n,o){function t(o){var t=n.getElementsByTagName("script")[0],i=n.createElement("script");i.src=o,i.crossOrigin="",t.parentNode.insertBefore(i,t)}if(!o.isLoyaltyLion){window.loyaltylion=o,void 0===window.lion&&(window.lion=o),o.version=2,o.isLoyaltyLion=!0;var i=new Date;t("https://<?php echo $this->getSDKUrl() ?>?t="+i.getFullYear()+i.getMonth()+i.getDate());var e=!1;o.init=function(n){if(e)throw new Error("Cannot call lion.init more than once");e=!0;var i=o._token=n.token;if(!i)throw new Error("Token must be supplied to lion.init");for(var r=[],a="_push configure bootstrap shutdown on removeListener".split(" "),l=0;l<a.length;l+=1)!function(n,o){n[o]=function(){r.push([o,Array.prototype.slice.call(arguments,0)])}}(o,a[l]);t("https://<?php echo $this->getPlatformHost() ?>/sdk/start/"+i+".js"),o._initData=n,o._buffer=r}}}(document,window.loyaltylion||[]);
    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
      <?php
        $customer = Mage::getSingleton('customer/session')->getCustomer();
        $now = date('c');
        $auth_src = $customer->getId() . $now . $this->getSecret();
      ?>
      loyaltylion.init({
        token: "<?php echo $this->getToken() ?>",
        customer: {
          id: "<?php echo $customer->getId() ?>",
          email: "<?php echo $customer->getEmail() ?>",
          name: "<?php echo $customer->getName() ?>"
        },
        auth: {
          date: "<?php echo $now ?>",
          token: "<?php echo sha1($auth_src) ?>"
        }
      });
    <?php else: ?>
      loyaltylion.init({ token: "<?php echo $this->getToken() ?>" })
    <?php endif ?>
  </script>
<?php endif ?>
